[file_paths]
robot_path = C:/Users/010200017/Documents/GitHub/pybullet-multi-grasp-sim/RobotURDFs/wbr_description/urdf/wbr_hand.urdf
; robot_path = C:/Users/010200017/Documents/GitHub/pybullet-multi-grasp-sim/RobotURDFs/barrett_hand_description/urdf/bh.urdf
; robot_path = C:/Users/010200017/Documents/GitHub/pybullet-multi-grasp-sim/RobotURDFs/finger_description/urdf/RH8D.urdf
object_path = C:/Users/010200017/Documents/GitHub/pybullet-multi-grasp-sim/ObjectURDFs/cylinder/cylinder_cap.urdf
; object_path = /home/kozai/pybullet-grasp/ObjectURDFs/sphere/sphere_small.urdf
object_scale = 1

[grasp_settings]
init_grasp_distance = .14
speed_find_distance = 1
grasp_distance_margin = .005
max_grasp_force = 0.3
target_grasp_velocity = .5
grasp_time_limit = 10.0
; barrett_hand
; active_grasp_joints = 3,6,9
; wbr_hand
; active_grasp_joints = 2,3,5,6,9,10
active_grasp_joints = 5,6
; RH8D
; active_grasp_joints = 4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
num_grasps_per_cycle = 1
num_cycles_to_grasp = 2
use_wrist_rotations = 0
num_wrist_rotations = 2

[eval_settings]
force_pyramid_sides = 8
force_pyramid_radius = .5

[gui_settings]
use_gui = 1
debug_lines = 0
debug_text = 1


